import type { CatalogProduct } from "@/lib/catalog-product";

export type MockProduct = CatalogProduct;

const IMG = {
  tyre: "/products/car-tyre.png",
  wheel: "/products/alloy-wheel.png",
  oil: "/products/motor-oil.png",
  battery: "/products/car-battery.png",
  brake: "/products/brake-disc.png",
};

export const mockProducts: MockProduct[] = [
  {
    id: "1",
    name: "Michelin Primacy 4",
    subtitle: "205/55 R16 91V",
    slug: "michelin-primacy-4-205-55-r16",
    price: 1_250_000,
    oldPrice: 1_650_000,
    discount: 24,
    rating: 4.8,
    reviewCount: 289,
    stock: 18,
    soldCount: 540,
    isActive: true,
    isApproved: true,
    isFeatured: true,
    images: [{ url: IMG.tyre }],
    brand: { name: "Michelin" },
    store: { name: "AutoParts Pro", slug: "autoparts-pro", isVerified: true },
    category: { id: "1", name: "Shinalar", slug: "shinalar" },
  },
  {
    id: "2",
    name: "Lenso Project D",
    subtitle: "R17 7.5J 5x114.3 ET45",
    slug: "lenso-project-d-r17",
    price: 2_100_000,
    oldPrice: 2_630_000,
    discount: 17,
    rating: 4.7,
    reviewCount: 96,
    stock: 12,
    soldCount: 210,
    isActive: true,
    isApproved: true,
    isFeatured: true,
    images: [{ url: IMG.wheel }],
    brand: { name: "Lenso" },
    store: { name: "WheelWorld", slug: "wheelworld", isVerified: true },
    category: { id: "2", name: "Disklar", slug: "disklar" },
  },
  {
    id: "3",
    name: "Castrol EDGE 5W-30",
    subtitle: "4L sintetik motor moyi",
    slug: "castrol-edge-5w30-4l",
    price: 580_000,
    oldPrice: 680_000,
    discount: 15,
    rating: 4.9,
    reviewCount: 201,
    stock: 45,
    soldCount: 760,
    isActive: true,
    isApproved: true,
    isFeatured: true,
    images: [{ url: IMG.oil }],
    brand: { name: "Castrol" },
    store: { name: "MotoShop", slug: "motoshop", isVerified: true },
    category: { id: "3", name: "Motor moylari", slug: "moylar" },
  },
  {
    id: "4",
    name: "VARTA Blue Dynamic",
    subtitle: "60Ah 540A akkumulyator",
    slug: "varta-blue-dynamic-60ah",
    price: 850_000,
    oldPrice: 980_000,
    discount: 13,
    rating: 4.6,
    reviewCount: 77,
    stock: 22,
    soldCount: 320,
    isActive: true,
    isApproved: true,
    isFeatured: true,
    images: [{ url: IMG.battery }],
    brand: { name: "VARTA" },
    store: { name: "ElectroAuto", slug: "electroauto", isVerified: true },
    category: { id: "4", name: "Akkumulyator", slug: "akkumulyator" },
  },
  {
    id: "5",
    name: "Brembo Brake Disc",
    subtitle: "Old ventilyatsiyali, R15–R20",
    slug: "brembo-brake-disc",
    price: 420_000,
    oldPrice: 520_000,
    discount: 19,
    rating: 4.7,
    reviewCount: 86,
    stock: 30,
    soldCount: 410,
    isActive: true,
    isApproved: true,
    isFeatured: true,
    images: [{ url: IMG.brake }],
    brand: { name: "Brembo" },
    store: { name: "BrakeShop", slug: "brakeshop", isVerified: true },
    category: { id: "5", name: "Tormoz tizimi", slug: "tormoz" },
  },
  {
    id: "6",
    name: "Bridgestone Turanza T005",
    subtitle: "215/55 R17 94W",
    slug: "bridgestone-turanza-t005-215-55-r17",
    price: 1_480_000,
    oldPrice: 1_720_000,
    discount: 14,
    rating: 4.6,
    reviewCount: 134,
    stock: 9,
    soldCount: 175,
    isActive: true,
    isApproved: true,
    isFeatured: false,
    images: [{ url: IMG.tyre }],
    brand: { name: "Bridgestone" },
    store: { name: "TyreWorld", slug: "tyre-world", isVerified: true },
    category: { id: "1", name: "Shinalar", slug: "shinalar" },
  },
  {
    id: "7",
    name: "Shell Helix Ultra 5W-40",
    subtitle: "4L to'liq sintetik",
    slug: "shell-helix-ultra-5w40-4l",
    price: 540_000,
    oldPrice: 620_000,
    discount: 13,
    rating: 4.8,
    reviewCount: 178,
    stock: 50,
    soldCount: 680,
    isActive: true,
    isApproved: true,
    isFeatured: false,
    images: [{ url: IMG.oil }],
    brand: { name: "Shell" },
    store: { name: "MotoShop", slug: "motoshop", isVerified: true },
    category: { id: "3", name: "Motor moylari", slug: "moylar" },
  },
  {
    id: "8",
    name: "Bosch S5 Silver",
    subtitle: "62Ah 600A akkumulyator",
    slug: "bosch-s5-silver-62ah",
    price: 890_000,
    oldPrice: 1_020_000,
    discount: 13,
    rating: 4.7,
    reviewCount: 92,
    stock: 16,
    soldCount: 240,
    isActive: true,
    isApproved: true,
    isFeatured: false,
    images: [{ url: IMG.battery }],
    brand: { name: "Bosch" },
    store: { name: "ElectroAuto", slug: "electroauto", isVerified: true },
    category: { id: "4", name: "Akkumulyator", slug: "akkumulyator" },
  },
  {
    id: "9",
    name: "Continental PremiumContact 6",
    subtitle: "225/45 R18 95Y",
    slug: "continental-premiumcontact-6-225-45-r18",
    price: 1_950_000,
    oldPrice: 2_250_000,
    discount: 13,
    rating: 4.9,
    reviewCount: 61,
    stock: 7,
    soldCount: 130,
    isActive: true,
    isApproved: true,
    isFeatured: false,
    images: [{ url: IMG.tyre }],
    brand: { name: "Continental" },
    store: { name: "AutoParts Pro", slug: "autoparts-pro", isVerified: true },
    category: { id: "1", name: "Shinalar", slug: "shinalar" },
  },
  {
    id: "10",
    name: "ATE Power Disc",
    subtitle: "Tormoz disklari, R16–R18",
    slug: "ate-power-disc",
    price: 380_000,
    oldPrice: 460_000,
    discount: 17,
    rating: 4.6,
    reviewCount: 74,
    stock: 26,
    soldCount: 290,
    isActive: true,
    isApproved: true,
    isFeatured: false,
    images: [{ url: IMG.brake }],
    brand: { name: "ATE" },
    store: { name: "BrakeShop", slug: "brakeshop", isVerified: false },
    category: { id: "5", name: "Tormoz tizimi", slug: "tormoz" },
  },
];

export const featuredProducts = mockProducts.filter((p) => p.isFeatured);
export const discountProducts = mockProducts.filter((p) => p.discount >= 15);
export const newProducts = [...mockProducts].reverse();
export const bestSellerProducts = [...mockProducts].sort((a, b) => b.soldCount - a.soldCount);
